#!/bin/bash


COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"
COLOR_YELLOW="\033[33m"
COLOR_BLUE="\033[34m"
COLOR_MAGENTA="\033[35m"
COLOR_CYAN="\033[36m"
COLOR_RESET="\033[0m"
MOVE_UP="\033[1A"
MOVE_DOWN="\033[1B"
MOVE_START="\033[0G"
CODE_ERRO="[${COLOR_RED}ERRO${COLOR_RESET}]\t"
CODE_WRNG="[${COLOR_YELLOW}WRNG${COLOR_RESET}]\t"
CODE_INFO="[${COLOR_CYAN}INFO${COLOR_RESET}]\t"
CODE_SUCC="${MOVE_UP}${MOVE_START}[${COLOR_GREEN} OK ${COLOR_RESET}]${MOVE_DOWN}${MOVE_START}"
CODE_FAIL="${MOVE_UP}${MOVE_START}[${COLOR_RED}FAIL${COLOR_RESET}]${MOVE_DOWN}${MOVE_START}"
LOG_DATE="$(date '+%Y-%m-%d %H:%M:%S')"
### ERROR MANAGEMENT ###########################################################

set -euo pipefail

function trap_errorr {
    printf "${CODE_ERRO} An unexpected error has ocurred. Exiting...\n"
}

trap trap_error ERR

### END ERROR MANAGEMENT #######################################################

GH_BINARY="./bin/gh"
GH_VERSION="2.88.1"
GH_CONFIGDIR="/tmp/gh-config"
ORGANIZATION="bonzosoft"
COMMON="common-tools"
PREDEPLOY="predeploy"


### FUNCTIONS ##################################################################

function main {    
    local param1="${1:?A command must be provided.}"
    local param2="${2:-}"

    if [[ ! -x "${GH_BINARY}" ]]; then
        gh_install
    fi

    case "${param1}" in
        "login")
            gh_login
            ;;
        "logout")
            gh_logout
            ;;
        "install")
            gh_install
            ;;
        *)
            case "${param2}" in
                "pull")
                    gh_pull "${param1}"
                    ;;
                "start")
                    compose_start "${param1}"
                    ;;
                "stop")
                    compose_stop "${param1}"
                    ;;
                *)
                    printf "${CODE_ERRO} Unknown parameter combination.\n"
                    return 1
                    ;;
            esac
            ;;
    esac

    return 0
}

function log() {
    local help=""
    local label=""
    local message=""
    local log=""

    COLOR_RED="\033[31m"
    COLOR_GREEN="\033[32m"
    COLOR_YELLOW="\033[33m"
    COLOR_BLUE="\033[34m"
    COLOR_MAGENTA="\033[35m"
    COLOR_CYAN="\033[36m"
    COLOR_RESET="\033[0m"
    MOVE_UP="\033[1A"
    MOVE_DOWN="\033[1B"
    MOVE_START="\033[0G"
    CODE_ERRO="[${COLOR_RED}ERRO${COLOR_RESET}]\t"
    CODE_WRNG="[${COLOR_YELLOW}WRNG${COLOR_RESET}]\t"
    CODE_INFO="[${COLOR_CYAN}INFO${COLOR_RESET}]\t"
    CODE_SUCC="${MOVE_UP}${MOVE_START}[${COLOR_GREEN} OK ${COLOR_RESET}]${MOVE_DOWN}${MOVE_START}"
    CODE_FAIL="${MOVE_UP}${MOVE_START}[${COLOR_RED}FAIL${COLOR_RESET}]${MOVE_DOWN}${MOVE_START}"
    #declare -A colors=(
    #   [INFO]="\033[36m"
    #   [WRNG]="\033[33m"
    #   [ERRO]="\033[31m"
    #   [SUCC]="\033[32m"
    #   [FAIL]="\033[31m"
    #)
    #if [[ -z "${colors[$label]}" ]]; then
    #    printf "[ERRO]\t Invalid label '%s'\n" "$label"
    #   return 1
    #fi

    while [[ ${#} -gt 0 ]]; do
        case "${1}" in
            -h|--help)
                # help message
                help=(
                    "Usage:"
                    "   log --label <INFO|WRNG|ERRO|SUCC|FAIL> --message <message>"
                    ""
                    "Description:"
                    "   Logs script progress."
                    ""
                    "Options:"
                    "   -l|--label      Label for the text format."
                    "   -m|--message    Message to be passed to the user."
                    "   -h|--help       Show this help."
                    ""
                    "Examples:"
                    "   log --label INFO --message 'Some info message.'"
                    ""
                )

                # print help message
                printf "%s\n" "${help[@]}"

                return 0
                ;;
            -l|--label)
                if [[ -z "${2}" || "${2}" == -* ]]; then
                    printf "[ERRO]\t A valid argument is required for option '%s'.\n" "${1}"
                    return 1
                else    
                    label="${2}"
                    shift 2
                fi
                ;;
            -m|--message)
                if [[ -z "${2}" || "${2}" == -* ]]; then
                    printf "[ERRO]\t A valid argument is required for option '%s'.\n" "${1}"
                    return 1
                else    
                    message="${2}"
                    shift 2
                fi
                ;;
            *)
                printf "[ERRO]\t Unknown option %s\n" "${1}"
                return 1
                ;;
        esac
    done

    if [[ -z "${label}" || -z "${message}" ]]; then
        printf "[ERRO]\t Missing mandatory option. Use -h|--help for more info.\n"
        return 1
    fi 

    # add label
    case "${label}" in 
        INFO)
            log="[${COLOR_CYAN}${label}${COLOR_RESET}]\t"
            ;;
        WRNG)
            log="[${COLOR_YELLOW}${label}${COLOR_RESET}]\t"
            ;;
        ERRO)
            log="[${COLOR_RED}${label}${COLOR_RESET}]\t"
            ;;
        SUCC)
            log="[${COLOR_GREEN}${label}${COLOR_RESET}]\t"
            ;;
        FAIL)
            log="[${COLOR_RED}${label}${COLOR_RESET}]\t"
            ;;
        *)
            printf "[ERRO]\t Invalid label '%s'. Use -h|--help for more info.\n" "${label}"
            return 1
    esac
    
    # add timestamp
    log+="$(date "+%Y-%m-%d %H:%M:%S.%N")\t"

    # add message
    log+="${message}"

    printf "%s\n" "${log}"

    return 0
}

function gh_check {
    local binary=${GH_BINARY}
    local configdir=${GH_CONFIGDIR}

    # validation
    if [[ -z "${binary}" ]]; then
        printf "${CODE_ERRO} 'GH' path not defined.\n"
        return 1
    fi

    if [[ ! -x "${binary}" ]]; then
        printf "${CODE_ERRO} 'GH' binary not found.\n"
        return 1
    fi

    if [[ -z "${configdir}" ]]; then
        printf "${CODE_ERRO} GH config directory not defined.\n"
        return 1
    fi

    return 0
}

function gh_install {
    printf "${CODE_INFO} Preparing the environment for 'GH'.\n"

    local binary=${GH_BINARY:?}
    local version=${GH_VERSION:?}
    local common=${COMMON:?}
    local tempfile=$(mktemp)
    
    # validation

    # logic
    printf "${CODE_INFO} Downloading 'GH'.\n"
    wget --quiet --output-document="${tempfile}" "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz"
    mkdir -p "$(dirname "${binary}")"
    tar --extract --gzip --strip-components=2 --directory="$(dirname "${binary}")" --file="${tempfile}" "gh_${version}_linux_amd64/bin/gh"
    chmod +x "${binary}"
    rm --force "${tempfile}"
    printf "${CODE_SUCC}"


    printf "${CODE_INFO} Downloading '%s'.\n" "${common}"
    gh_pull "${common}" 
    #git clone "https://github.com/${ORGANIZATION}/${common}.git" "${common}"
    printf "${CODE_SUCC}"

    return 0
}

function gh_login {
    printf "${CODE_INFO} Starting GitHub interactive login.\n"

    local binary=${GH_BINARY:?}

    # validation
    gh_check

    # logic
    "${binary}" auth login --hostname github.com --git-protocol https --web
    "${binary}" auth setup-git

    printf "${CODE_SUCC}"
    return 0
}

function gh_logout {
    printf "${CODE_INFO} Closing GitHub session.\n"

    local configdir=${GH_CONFIGDIR:?}
    
    # logic
    if [[ -d "${configdir}" ]]; then
        rm --recursive --force "${configdir}" > /dev/null
    fi

    printf "${CODE_SUCC}"
    return 0
}

function gh_pull {
    printf "${CODE_INFO} Pulling GitHub repository.\n"

    local binary=${GH_BINARY}
    local organization=${ORGANIZATION:?}
    local name=$1
    local branch=${2:-main}

    # validation
    gh_check

    if [[ -z "${name}" ]]; then
        printf "${CODE_ERRO} Repository name must be provided.\n"
        return 1
    fi

    # logic
    if [[ ! -d "${name}" ]]; then
        printf "${CODE_INFO} Initializing repository '%s'.\n" "${name}"

        "${binary}" repo clone "${organization}/${name}" "./${name}" > /dev/null # 2>&1
    fi

    printf "${CODE_INFO} Updating repository '%s'.\n" "${name}"

    pushd "./${name}" > /dev/null
    "../${binary}" repo sync --branch "${branch}" --force > /dev/null # 2>&1
    git submodule update --init --recursive > /dev/null # 2>&1
    popd > /dev/null

    printf "${CODE_SUCC}"
    return 0
}

function compose_start {
    local name="${1:?}"
    local predeploy="${PREDEPLOY:?}"

    if [[ -d "${name}" ]]; then
        printf "${CODE_INFO} Starting '%s'.\n" "${name}"
    else
        printf "${CODE_ERRO} Target '%s' not available.\n" "${name}"
        return 1
    fi

    pushd "./${name}" > /dev/null
    if [[ -f "./${predeploy}" ]]; then
        bash "./${predeploy}" --realm "prod"
    fi
    docker compose up -d
    #docker compose -p "ix-${name}" up -d
    popd > /dev/null
}

function compose_stop {
    local name="${1:?}"
    
    if [[ -d "${name}" ]]; then
        printf "${CODE_INFO} Stopping '%s'.\n" "${name}"
    else
        printf "${CODE_ERRO} Target '%s' not available.\n" "${name}"
        return 1
    fi

    pushd "./${name}" > /dev/null
    docker compose down
    #docker compose -p "ix-${name}" down
    popd > /dev/null
}
### END FUNCTIONS ##############################################################

main "${@}"