name: Fetch and Package Modules from bonzosoft/common

on:
  push:
    paths:
      - './.github/workflows/version' # Run workflow when the 'version' file is updated
    branches:
      - main
  workflow_dispatch: # Run on demmand


permissions:
  contents: write # Permissions for commits in bootstrap

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checktout bootstrap
        uses: actions/checkout@v7
        with:
          path: bootstrap

      - name: 📖 Get common repository commit/tag 
        id: read_version
        shell: pwsh
        run: |
          $commitId = (Get-Content -Path "./bootstrap/.github/workflows/version" -Raw).Trim()
          
          Write-Output "Requested commit/tag: $commitId"
          
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ref_target=$commitId"

      - name: 📥 Checkout requested common repository commit/tag
        uses: actions/checkout@v7
        with:
          repository: bonzosoft/common
          path: common
          ref: ${{ steps.read_version.outputs.ref_target }}
          token: ${{ secrets.CONTENTS_READONLY_COMMONS }}
          fetch-depth: 0 # all commit history, default = 1

      - name: 🗜️ Add pwsh modules to archive
        shell: pwsh
        run: |
          Write-Output "Adding modules..."
          Compress-Archive -Path ./common/modules/* -DestinationPath ./bootstrap/modules.zip -Force

      - name: 📤 Commit changes to bootstrap
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          repository: bootstrap
          commit_message: "AutoUpdate PowerShell modules"
          file_pattern: modules.zip
