name: Fetch and Package Modules

on:
  push:
    # Ahora vigila el archivo 'version' sin extensión .txt
    paths:
      - 'version'
    branches:
      - main
  # Botón manual para lanzarlo a demanda
  workflow_dispatch:

# Permisos para poder hacer el commit en bootstrap
permissions:
  contents: write

jobs:
  fetch-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar repositorio actual (bootstrap)
        uses: actions/checkout@v7
        with:
          path: bootstrap

      - name: 📖 Leer la versión deseada
        id: read_version
        shell: pwsh
        run: |
          # Leemos el contenido del archivo 'version'
          $commitId = Get-Content -Path "./bootstrap/version" -Raw
          $commitId = $commitId.Trim()
          
          Write-Output "Se solicitó el commit/tag: $commitId"
          
          # Escribimos en el archivo temporal de GitHub usando cmdlets nativos
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ref_target=$commitId"

      - name: 📥 Descargar repositorio origen (common)
        uses: actions/checkout@v7
        with:
          # Repositorio apuntando a la organización bonzosoft
          repository: bonzosoft/common
          path: common
          ref: ${{ steps.read_version.outputs.ref_target }}
          # Token de solo lectura guardado en tus Repository Secrets
          token: ${{ secrets.CONTENTS_READONLY_COMMONS }}

      - name: 🗜️ Comprimir directorio de módulos
        shell: pwsh
        run: |
          Write-Output "Comprimiendo módulos..."
          Compress-Archive -Path ./common/modules/* -DestinationPath ./bootstrap/modules.zip -Force

      - name: 📤 Guardar (Checkin) el archivo zip actualizado
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './bootstrap'
          message: "Auto-update: Módulos empaquetados desde la versión ${{ steps.read_version.outputs.ref_target }}"
          add: 'modules.zip'
          